version: '3.1'

services:

  api-database:
    image: postgres
    ports:
      - "5432:5432"

    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  api-service:
    build: api/.
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - api-database

  worker-database:
    image: redis
    ports:
      - 6379:6379

  worker-service:
    build: worker/.
    command: bash -c "celery -A worker worker -l info"
    depends_on:
     - worker-database
     - api-database 
    