# Generated by Django 2.2.28 on 2022-07-05 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220705_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='repo',
            name='createdAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
