# Generated by Django 2.2.28 on 2022-07-05 21:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_repo_createdat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repo',
            name='sha',
        ),
        migrations.AddField(
            model_name='repo',
            name='owner',
            field=models.CharField(
                default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
