# Generated by Django 2.2.28 on 2022-07-05 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220705_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repo',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
