# Generated by Django 2.2.28 on 2022-07-05 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20220705_2235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repo',
            old_name='dataCriada',
            new_name='createdAt',
        ),
    ]
