# Generated by Django 2.2.28 on 2022-07-05 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20220705_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='cached',
            field=models.BooleanField(default=True),
        ),
    ]
