# Generated by Django 2.2.28 on 2022-07-05 22:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0005_auto_20220705_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='repo',
            name='teste',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
