# Generated by Django 2.2.28 on 2022-07-05 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0006_repo_teste'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repo',
            old_name='createdAt',
            new_name='dataCriada',
        ),
        migrations.RemoveField(
            model_name='repo',
            name='teste',
        ),
    ]
