# Generated by Django 2.2.28 on 2022-07-05 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0008_auto_20220705_2236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repo',
            old_name='createdAt',
            new_name='created_at',
        ),
    ]
