# Generated by Django 2.2.28 on 2022-07-11 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0010_commit_cached'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commit',
            name='cached',
        ),
    ]
