# Generated by Django 2.2.28 on 2022-07-11 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0011_remove_commit_cached'),
    ]

    operations = [
        migrations.AddField(
            model_name='repo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
